### ISSUE TITLE
Release with VS2015 support

### ISSUE THREAD

**Issue by neusdan** [vslavik/bakefile#83]
I'd like to ask again (#68) if there are any plans for a new release? The last release is more than 2 years ago.  Even an alpha oder beta version would help. Thanks.

**Comment by vslavik** [comment]
Use git master.

If you don’t want and want releases, *do* something about it — setup Travis and AppVeyor builds that create packages, submit a PR for it and making releases will become as simple as `git tag -s`.

**Comment by neusdan** [comment]
I wouldn't ask if i were able to get an executable from the master branch. 
And yes i have read all READMEs and tried a lot, but still had no success with this.

**Comment by vslavik** [comment]
> read all READMEs and tried a lot, but still had no success with this.

Yet you didn’t file a single bug report? Either you didn’t follow the instructions precisely (in which case, do) or you *did* — in which case either the documentation is too vague and ambiguous or there’s a bug (or bugs) in the makefiles. Either way it calls for a PR or a bug report instead of such awfully vague innuendo...

**Comment by neusdan** [comment]
Maybe i give it another try and fill a bug report but honestly i don't like your tone and attitude. That's neither very helpful nor motivating.

**Comment by vadz** [comment]
@neusdan I do plan to make another release "soon", but I just don't have any time at all right now. Please do open issues if you run into anything until then. Thanks!
