### ISSUE TITLE
Please release a new legacy branch version

### ISSUE THREAD

**Issue by swt2c** [vslavik/bakefile#86]
wx still uses the legacy branch and version 0.29 is broken (without the swig patch in git).  It would be helpful to have a new release of the legacy branch.

**Comment by vadz** [comment]
I've created [the release](https://github.com/vslavik/bakefile/releases/tag/v0.2.10) but I have no idea how to build MSW and OSX binaries, so I didn't do it. As the crash mostly affects Linux, hopefully the tarball should be enough.

**Comment by vslavik** [comment]
> As the crash mostly affects Linux, hopefully the tarball should be enough.

I think it may affect macOS too and in any case, there were some other minor fixes since 0.2.9 and the macOS package is non-functional and neither macOS nor Windows binaries are signed, so I think a proper "farewell" release with binaries would be useful for wx's needs.

> but I have no idea how to build MSW and OSX binaries,

These times, by inspecting `build/` and doing the same or similar stuff manually.

I just did that for macOS and unloaded it to the release — seems to work fine (except a warning about XML cache that I'm not going to waste time fixing, it doesn't affect functionality). That archeological feat was exhausting and time-consuming enough, so I'll treat myself to a small break before following with Windows installer.

**Comment by vslavik** [comment]
…and Windows package is uploaded too. Added `PACKAGING_LEGACY.md` with some barebones instructions should this be necessary again (hopefully not).
